# -*- coding: utf-8 -*-
"""Problem1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B2HdI8ePp3J0DpDF58m89OcaJh_SeLmC
"""

import numpy as np
import scipy as sp


def k_init(X, k):
    """ k-means++: initialization algorithm

    Parameters
    ----------
    X: array, shape(n ,d)
        Input array of n samples and d features

    k: int
        The number of clusters

    Returns
    -------
    init_centers: array (k, d)
        The initialize centers for kmeans++
    """
    # first we want to initialize the first center c1 uniformly at random from the training data
    random_row = X[np.random.choice(X.shape[0])]
    init_centers = [random_row]

    # loop through the K clusters
    for i in range(1, k):
      dist_list = []
      #loop through each of the datapoints
      for j in range(X.shape[0]):
      # find the distance for each point j to the centers currently in the list
      # the formula for this is given in the slides
        dist_j = min(np.linalg.norm(X[j] - center)**2 for center in init_centers)
        dist_list.append(dist_j)

      # computing the chance of every data point to be the next center, after we have the full list of distances to the center
      prob_j = [dist_list[q]/sum(dist_list) for q in range(len(dist_list))]


      # choosing the next center ci to be one of the data points based on the probability we calculated
      next_center = X[np.random.choice(X.shape[0], p=prob_j)]
      init_centers.append(next_center)

    return np.array(init_centers)


def k_means_pp(X, k, max_iter):
    """ k-means++ clustering algorithm

    step 1: call k_init() to initialize the centers
    step 2: iteratively refine the assignments

    Parameters
    ----------
    X: array, shape(n ,d)
        Input array of n samples and d features

    k: int
        The number of clusters

    max_iter: int
        Maximum number of iteration

    Returns
    -------
    final_centers: array, shape (k, d)
        The final cluster centers
    """
    # step 1 initializing the centers
    final_centers = k_init(X, k)




    objectives = []
     # iteratively refine the assignments

    for i in range(max_iter):
      Assignments = assign_data2clusters(X, final_centers)
      # print(Assignments.shape)
      # print(X.shape)
      # the average of the points that are assigned to a particular cluster
      # only taking rows where the j column is "1" meaning it belongs to that cluster, and averaging them
      C = np.array([X[Assignments[:, j] == 1].mean(axis=0) for j in range(k)])
      loss = compute_objective(X, C)
      objectives.append(loss)

      final_centers = C


    return final_centers, objectives


def assign_data2clusters(X, C):
    """ Assignments of data to the clusters
    Parameters
    ----------
    X: array, shape(n ,d)
        Input array of n samples and d features

    C: array, shape(k ,d)
        The final cluster centers

    Returns
    -------
    data_map: array, shape(n, k)
        The binary matrix A which shows the assignments of data points (X) to
        the input centers (C).
    """
    #initializing the data map to 0s
    data_map = np.zeros((X.shape[0], C.shape[0]))

    #loop through all data points
    for i in range(X.shape[0]):
      #calculate Euclidean distance
      clust_assign = np.argmin([np.linalg.norm(X[i] - center)**2 for center in C])

      # create data map with assignments of a signular data point to the nearest cluster
      data_map[i, clust_assign] = 1

    return data_map


def compute_objective(X, C):
    """ Compute the clustering objective for X and C
    Parameters
    ----------
    X: array, shape(n ,d)
        Input array of n samples and d features

    C: array, shape(k ,d)
        The final cluster centers

    Returns
    -------
    accuracy: float
        The objective for the given assigments
    """
    # intialize this objective to 0
    objective = 0

    #loop through all data points
    for i in range(X.shape[0]):
      #calculate Euclidean distance
      dist_to_nearest_cluster = min([np.linalg.norm(X[i] - center)**2 for center in C])

      # add this distance to the objective
      objective += dist_to_nearest_cluster

      # find the average of the objective over all the samples
      accuracy = objective/X.shape[0]

    return objective